

var data_cols = ["", "university", "course", "link"]
var wedlock_data = [
['','charles sturt university', 'associate degree in adult and vocational education', 'https://futurestudents.csu.edu.au/courses/teaching-education/associate-degree-adult-vocational-education'],
['','charles sturt university', 'associate degree in policing practice', 'https://futurestudents.csu.edu.au/courses/police-security-emergency/associate-degree-policing-practice'],
['','charles sturt university', 'bachelor of accounting', 'https://futurestudents.csu.edu.au/courses/business/bachelor-accounting'],
['','charles sturt university', 'bachelor of adult and vocational education (with specialisations)', 'https://futurestudents.csu.edu.au/courses/teaching-education/bachelor-adult-vocational-education'],
['','charles sturt university', 'bachelor of agricultural business management', 'https://futurestudents.csu.edu.au/courses/business/agribusiness https://futurestudents.csu.edu.au/courses/business/agribusiness'],
['','charles sturt university', 'bachelor of agricultural science', 'https://futurestudents.csu.edu.au/courses/agricultural-wine-sciences/bachelor-agricultural-science'],
['','charles sturt university', 'bachelor of agriculture', 'https://futurestudents.csu.edu.au/courses/agricultural-wine-sciences/bachelor-agriculture'],
['','charles sturt university', 'bachelor of animal science', 'https://futurestudents.csu.edu.au/courses/animal-vet-sciences/bachelor-animal-science'],
['','charles sturt university', 'bachelor of applied science (outdoor recreation and  ecotourism)', 'https://futurestudents.csu.edu.au/courses/environmental-outdoor/bachelor-applied-science-outdoor-recreation-ecotourism'],

]
var additional_info = []
var stop_words = [
"aboard",
"about",
"above",
"across",
"after",
"against",
"along",
"amid",
"among",
"anti",
"around",
"as",
"at",
"before",
"behind",
"below",
"beneath",
"beside",
"besides",
"between",
"beyond",
"but",
"by",
"concerning",
"considering",
"despite",
"down",
"during",
"except",
"excepting",
"excluding",
"following",
"for",
"from",
"in",
"inside",
"into",
"like",
"minus",
"near",
"of",
"off",
"on",
"onto",
"opposite",
"outside",
"over",
"past",
"per",
"plus",
"regarding",
"round",
"save",
"since",
"than",
"through",
"to",
"toward",
"towards",
"under",
"underneath",
"unlike",
"until",
"up",
"upon",
"versus",
"via",
"with",
"within",
"without"]


var keywords_data = {
    profession: [
      'engineer',
      'Doctor',
      'craftsmen',
      'nil',
      'Scientist',
      'Other',
      'student',
      'buisness owner',
      'journalist',
      'writer',
      'artist',
      'HR ',
      'reporter',
      'business owner',
      'cricketer',
      'goverment worker',
      'Goverment servent',
      'profession1',
      "doctor",
      "engineer",
      "teacher",
      "business man",
      "nurse",
      "pilot",
      "police",
      "lawyer",
    ],
    religion: [
        'parsi',
        'jewish',
      "muslim",
      "hindu",
      "sikh",
      "jain",
      "bhuddist",
      "christian",
    ],
    location: [
        "hyderabad",
        "delhi",
        "mumbai",
        "jammu",
        "bangalore",
        "goa"],
    gender:[
        "male",
        "female",
        "others"
    ],
    caste: [
      "singh",
      "marwadi",
      "kayast",
      "brahman",
      "sunni",
      "sheikh",
      "mohammad",
      "syed",
      "reddy",
      "shia"]
  };


  var nearly_matching_words = {
    caste: [
      ["singh", "sing", "seeng", "sengh", "sin"],
      ["marwadi", "maradi", "marvadi", "marwati", "meradi", "marwade"],
      ["kayast", "kayasht", "kayest", "caste", "kayasath", "kaya", "cast"],
      ["brahman", "barahaman", "barahman", "braman", "bramin"],
      ["sunni", "sony", "suny", "sunny"],
      ["sheikh", "shaik", "shaik", "shake", "shek", "sheikh", "sher"],
      ["mohammad", "mohammed", "muhammed", "mohamed", "mohammat"],
      ["syed", "sayyad", "seyyed", "sayyed", "sayed", "said"],
      ["shia", "shah", "shaah"],
    ],
    gender: [
      ["male", "mal", "malu", "main", "mel", "mail", "men", "man","boy"],
      ["female", "femail", "fimal", "femin","woman","girl"],
    ],
    religion: [
      ["sikh", "sik", "seak", "seek", "sick", "seekh"],
      ["hindu", "hind", "hindhu", "hinda", "hendu", "hinder"],
      ["muslim", "muslem", "muslam", "musleem", "moslim", "mus"],
      ["bhuddist", "bhuddis", "buddist", "bhuddisth", "bhud"],
      ["christian", "cristian", "christan", "christin", "chris"],
    ],
    location: [
      ["hyderabad", "hyder", "hyderaba"],
      ["delhi", "daily", "deli", "del"],
      ["goa", "gauva", "go", "gowa", "gova", "gua"],
      ["mumbai", "mum", "mumba", "mombai", "bombay"],
      ["kerela", "karela", "kerel", "kerale"],
    ],
    profession: [
      ["engineer", "engineering", "engine", "engg", "gineer", "enggine"],
      ["artist", "act", "art", "acter", "actress", "atre"],
      ["scientist", "science", "scientific", "scientest"],
      ["cricketer", "cricket", "batman", "bowler", "cirik", "cricat"],
      ["writer", "novelist", "story writer", "series writer", "writar"],
      ["nurse", "compounder", "nurze", "sister"],
      ["teacher", "miss", "sir", "professor", "lecture", "lecturer"],
      ["programmer", "programer", "techee", "programmar"],
      ["fashion designer", "designer", "fasion designer"],
      ["driver", "traveller", "drivar"],
      ["doctor", "doc", "docto", "docc", "doctar", "doccotor"],
      ["architect", "arch", "arc", "archichit", "arcch", "archit", "chitect"],
      ["student", "stud", "stuent", "stu", "studant"],
      ["pilot", "pilat", "pilet", "pilo", "pile"],
      ["dentist", "dantist", "dentu", "dant", "dent"],
      ["chef", "chaf", "cook", "chief chef"],
    ],
    language: [
      ["hindi", "hinda", "hindee", "hind"],
      ["english", "eng"],
      ["tamil", "tamel"],
      ["urdu", "urd"],
      ["telugu", "tel"],
      ["bengali", "bengal"],
    ],
    age: [[20],[21],[22],[23],[24],[25],[26],[27],[28],[29],[30],[31],[32],[33],[34],[35],[36],[37],[38],[39],[40],[45],[50]]
  };